#! /usr/bin/env zsh

function main {
  LD_LIBRARY_PATH=LD_LIBRARY_PATH:$HOME/.development/books/sherriff-learn_qt5/cm-02/cm-lib/_build ./cm-ui/_build/cm-ui
}

main $@

# vim: set textwidth=80 colorcolumn=80:
